### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Surf-N-Code** [codereviewvideos/beginners-guide-symfony-3-form#1]
Just found your tutorials on google and landed here. I think you missed adding the entity files and some other files to git? At least I cannot find them in the repo :)

**Comment by codereviewvideos** [comment]
Hi @Surf-N-Code - unless I've misunderstood, you should be able to find everything you need for each tutorial on a separate branch:

https://github.com/codereviewvideos/beginners-guide-symfony-3-form/branches

It's not obvious from the tutorials though, so apologies for that. 

Just FYI, I wrote them 3+ years ago. Hopefully the content is still relevant, but if using with Symfony 5 (or latest, I don't use Symfony much anymore) then things may have changed. 

Closing, but feel free to reopen if I have not resolved :)
